cors:
  originPatterns: https://localhost:8080
file:
  upload-dir: /Users/arthu/temp/upload-dir
security:
  jwt:
    token:
      secret-key: 51bp09
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-springboot-udemy?useTimezone=true&serverTimezone=UTC
    username: root
    password: sacola07
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: false
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  paths-to-match: 
    - /auth/**
    - /api/**
  swagger-ui:
    use-root-path: true